### ISSUE TITLE
Very excited about this plugin

### ISSUE THREAD

**Issue by erex** [SkepticMystic/email-templates#1]
The existence of this plugin finally caused me to install BRAT, just so I could give it a go.  My email inbox is not supposed to be used as a filing system, but I suspect I'm not the only one who uses it in that way.  Having messages within Obsidian is the obvious way to track messages and link concepts.

OS: Windows 10
Obsidian version: 0.12.19

I understand from the Discord discussion you were able to put together this plugin quickly, so it is to be expected that it has some rough edges.

My experiment this morning with four downloaded Outlook messages produced a success rate of 50%.  Two messages imported just fine, two did not (nothing happened when pressing the hotkey assigned to `Import Emails`).  Below is a screen grab of the console log

![image](https://user-images.githubusercontent.com/330744/146165293-c295b7a8-f08c-4b42-a287-72b8262424ce.png)

Plugin behaviour is also odd when viewing the template
![image](https://user-images.githubusercontent.com/330744/146165569-fddafe99-1718-41a0-b493-5d69a47d085a.png)

Thanks again for the plugin and looking forward to developments.

**Comment by SkepticMystic** [comment]
Haha I'm very glad to hear you might find this useful! :D
Thank you for the bug reports. I think I have resolved the issue in the latest release, can you give it a try when you're able to?
I have also made the template textarea taller.

If you are at all open to it, could you dm me some example emails that gave you issues? Just so I can add some tests to avoid these issues later. I obvs understand if not, but maybe there are some less private ones you don't mind sharing :)

**Comment by erex** [comment]
Installed the 0.0.6 update, no problems.  Imported the two emails that would not install this morning and the text window is larger.  I would send you emails in future that fail so you can test against them.

In a perfect world, I would like to have the hard returns in text body removed, but perhaps there is a different plugin that can find that battle.  I would also like the option of eliminating the preceeding quoted message from the message being imported.

I'll have to mess about with the template to see what flexibility this can offer.

**Comment by SkepticMystic** [comment]
I like both of these ideas. Can you please make 2 separate FRs for 'em, and I'll see what I can do :)
